title_tag_text: schöne might - Agentur für vernetztes Marketing, Markenkommunikation & Gestaltung
h1_tag_text: schöne might

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
